name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.22.2
      - name: install
        run: |
          pnpm install
          pnpm lint
        env:
          CI: true
